### PR TITLE
Add color rotation and graphic design vendor

### PR DESCRIPTION
**Pull request by thatdocslady**

### CODE REVIEW

**Comment by ericholscher** [comment]
What's the plan for the shirts and other assets? If we start re-using colors, they lose their year-specific meaning, so I feel like we should change the downstream designs to either include the year again, or change the design.

**Comment by thatdocslady** [comment]
@ericholscher the point of rotating colors is so that we don't need to bust our heads every year trying to find a new color (which I can totally get behind). I'm ok with bringing back the year to the printed swag, I'm sure Phoenix can make it work without changing the overall design too much.

**Comment by ericholscher** [comment]
Yea, I think I'm :+1: on adding years back to the designs and keeping the colors. That works well for me. 

I think we talked about doing a larger design revamp once we hit the end of the color rotation, but that doesn't seem in the cards for this year, but we should do the small adjustment.

**Comment by thatdocslady** [comment]
@mxsasha @plaindocs thumbs up/down/sideways? :D

**Review by mxsasha — APPROVED** [review]

**Pull request merged**
