### PR TITLE
Resize Prague text larger

### PR DESCRIPTION
**Pull request by agjohnson**

### CODE REVIEW

**Comment by thatdocslady** [comment]
@agjohnson it looks like the Prague text is still not aligned correctly. From what I see in the Portland version, the text should be aligned with the outside borders of the top word "Write", and basically fill the entire bottom of the square. I hope that makes sense and that it's possible? Let me know if you want to discuss in real-time. Same comment for hoodies.

**Comment by agjohnson** [comment]
I'll give it a shot. That width wasn't an important part of the design though. This may bump up the font size to larger than the above font, which definitely wouldn't work

**Comment by agjohnson** [comment]
Updated. Font sizing is close, but far enough that the Prague text isn't overshadowing. I'm mostly impartial to the change, but think it looks good still.

**Comment by thatdocslady** [comment]
@agjohnson perfect, thank you so much!

**Pull request merged**
